[rpc]

# this is the config file for Geometry Dash RPC
# in each string, if specified, you can write name of the attribute to display
# for that you would use curly brackets {...}, like {name}

# general RPC setup

process_name = "default"
refresh_rate = 1  # seconds between presence refreshing
client_id = 704721375050334300  # client ID, change only if you are using your own version

[rpc.editor]

# these used when you are in the editor
# available keys:
# - level_name
# - object_count
# - user_name

details = "Editing level"
state = "{level_name} ({object_count} objects)"

[rpc.level]

# these are used when you are playing a level
# available keys:
# - percent (current)
# - best_normal
# - best_practice
# - attempt
# - mode (see rpc.mode)
# - gamemode (see rpc.gamemode)
# - level_id
# - level_name
# - level_creator
# - level_difficulty (see rpc.difficulty)
# - level_stars
# - level_type (see rpc.level_type)

details = "{level_name} (attempt {attempt}) <{gamemode}> [{level_type}]"
state = "by {level_creator} ({mode} {percent}%, best {best_normal}%/{best_practice}%)"
small_text = "{level_stars}* {level_difficulty} (ID: {level_id})"

percent_precision = 1  # decimal places for percentage displaying

[rpc.scene]

# these are used when you are not editing/playing anything

main = "Idle"
select = "Selecting level"
editor_or_level = "Watching level info"
search = "Searching levels"
leaderboard = "Browsing leaderboards"
online = "Online"
official_levels = "Selecting official level"
official_level = "Playing official level"

[rpc.difficulty]

# these are used to display level difficulties

na = "N/A"
auto = "Auto"
easy = "Easy"
normal = "Normal"
hard = "Hard"
harder = "Harder"
insane = "Insane"
demon = "Demon"

# these are used to display demon level difficulties

easy_demon = "Easy Demon"
medium_demon = "Medium Demon"
hard_demon = "Hard Demon"
insane_demon = "Insane Demon"
extreme_demon = "Extreme Demon"

[rpc.gamemode]

# these are used to display gamemodes

cube = "cube"
ship = "ship"
ball = "ball"
ufo = "ufo"
wave = "wave"
robot = "robot"
spider = "spider"

[rpc.level_type]

# these are used to display level types

null = "null"
official = "official"
editor = "editor"
saved = "saved"
online = "online"

[rpc.mode]

# these are used to display current mode

normal = "normal"
practice = "practice"
